cevich/ADEPT

roles/autotested/tasks/configure_defaults.yml, roles/autotested/tasks/test_image_fqin.yml
First commit fixes a bug with this, second one allows setting ``preserve_fqin_cmd`` to something like ``docker images --no-trunc --all --quiet | tr '[:space:]' ','``
=> Make using images w/o predefined hostname easier

roles/autotested/defaults/main.yml, roles/autotested/tasks/configure_control.yml, roles/autotested/tasks/configure_defaults.yml
This approach worked at one point, but is poorly designed.  These
tasks are to support docker-autotest subtests which no longer exist.
The underlying calls also need to be reimplemented as per:
https://github.com/autotest/autotest-docker/issues/612
=> Disable restart the docker daemon using alternate options

files/variables.yml, vars/peons.yml
=> Fix default adept_job and missing fedoratomic peon

roles/autotested/tasks/main.yml
The autotested role first transfers a copy of the autotest repository to
the test VM.  If recursive submodules were used to clone that repo,
it will include a (likely very) old version of docker autotest.  Later,
when the cached (modern) docker-autotest is also transfered, it will end
up with bits that have long since been removed.
Fix this by first removing the docker autotest path before doing the
cache copy.
=> Fix Autotest/Docker Autotest cache clash

roles/autotested/tasks/produce_results.yml, roles/openstack/tasks/setup.yml
Test VMs (peons) are all assigned a globally unique name to prevent
clashes with concurrently running jobs.  This is not a good name to use
for tagging test results because they will never align from run-to-run.
This change makes the peon and cloud metadata available to them via
host_vars.  Later, when the autotest role is applied, it's possible to
extract the peon's uncompounded (basic definition) name.  This is
guaranteed unique within a run, but will be (mostly) shared across
them.
=> Pass peon metadata name into results2junit

roles/subscribed/defaults/main.yml, roles/subscribed/tasks/main.yml
=> Support specifying alternate RHSM URLs.

group_vars/centosatomic/storage.yml, group_vars/fedoratomic/storage.yml, group_vars/rhelatomic/storage.yml, peons.yml, roles/atomic_upgrade/tasks/main.yml, roles/lvm/defaults/main.yml, roles/lvm/tasks/main.yml, roles/touchstone/tasks/main.yml
Also, give a known fixed size for root storage on atomic hosts and add beginnings of feature to support detection of partially-setup hosts.
=> Fix ignored-failure on atomic upgrade

roles/autotested/tasks/produce_results.yml
The new results2junit failed with:
fatal: [centos-7-2-ADEPT-dockerautotest-...]: FAILED! => {...
"cmd": "/var/lib/autotest/client/tests/docker/results2junit\n --name centos\n results/default",
...,
"stderr": "usage: results2junit [-h] [-v] [-n] [--name NAME] autotest_results_dir\nresults2junit: error: too few arguments\n/bin/sh: line 1: --name: command not found\n/bin/sh: line 2: results/default: Is a directory",
...
Cause: ansible is passing the command with newlines.
Solution: back to just one line
=> Sigh. Remove newlines from results2junit call

roles/atomic_upgrade/tasks/main.yml, roles/autotested/templates/control.ini.j2
Simplify failed/changed conditions, guarantee the _needs_upgrade is set
in local scope, and don't check atomic_host_upgrade if _needs_upgrade is
false. This fixes a problem where there is no upgrade available, causing the
upgrade block to be bypassed. This means the atomic_host_upgrade is
undefined, though referenced after the block.
=> Fix atomic_upgrade and build/git_path template comments

roles/atomic_upgrade/tasks/main.yml
This is used as an indication of "No upgrade available, only downgrade".
Update task conditions to accept this.
=> The atomic --check-diff exits non-zero on success

roles/slave/tasks/cleanup.yml, roles/slave/tasks/main.yml
"Bad things happen" when there's no more room for workspaces.  The
localhost (slave) role occurs last during cleanup, so all important
details were already synchronized out.  Eventually the disk will still
fill up, but that's a problem for another time.
=> Slow down rate of kommandir disk filling

group_vars/docker-latest.yml, roles/autotested/defaults/main.yml, roles/autotested/tasks/main.yml, roles/docker-storage-setup/defaults/main.yml, roles/docker-storage-setup/tasks/main.yml
Some jobs are failing in the autotested role due to undefined variable.  All docker-latest peons with non-default d-s-s configuration should be using ``/etc/sysconfig/docker-latest-storage-setup`` instead.
=> Important fixes

roles/docker-storage-setup/defaults/main.yml, roles/docker-storage-setup/tasks/main.yml
Later versions of the atomic storage reset command misidentify the
empty /var/lib/docker-latest and issue an error message.  Fix this
by removing the tasks which run atomic storage reset.  This works
in all cases because any atomic hosts have already setup by cloud-init
and non-atomic hosts have not started any services yet.
Also, block the d-s-s role with conditionals so that the docker service state
isn't affected if no d-s-s changes are requested.
=> Workaround RH BZ 1411948

roles/subscribed/tasks/main.yml
Don't fail the host if it's already registered, this is the desired state.
=> Fix registered system re-registration failed.

group_vars/docker-latest.yml, peons.yml, roles/docker-storage-setup/defaults/main.yml, roles/docker-storage-setup/tasks/main.yml
The docker-latest group variables file had a misspelling of
a variable name that was causing the incorrect file to be updated:
/etc/sysconfig/docker-storage-setup
instead of
/etc/sysconfig/docker-latest-storage-setup
Also, the d-s-s role was being applied before /etc/sysconfig/docker had
it's DOCKERBINARY updated to docker-latest.  Fixed by re-ordering the
roles in peons.yml
=> Fix docker-latest / d-s-s group var + role order

roles/docker-storage-setup/tasks/main.yml
Even if /etc/sysconfig/d-s-s or docker-latest-s-s is re-configured, if
either /var/lib/docker* directory exists, then d-s-s will not run.
Also, on newer docker-latest packages, d-s-s needs to be called as:
docker-latest-storage-setup.  Rather than try and guess which to use,
when, just remove both directories and allow the docker/docker-latest
systemd services to "do the right thing".
=> Fix d-s-s not running if dir exists

roles/yumrepos/defaults/main.yml, roles/yumrepos/tasks/main.yml
No idea why 'exclude' was used, probably a copy-paste typo on my part.
Also defaulting to 'False' (i.e. --nogpgcheck) isn't the correct
behavior.  It's important to spot instances where packages are unsigned,
and they should be.  This change will cause those cases to (correctly)
fail.
For cases where development/test repos. are being used, their
list item args will need to be updated with 'gpgcheck: False'
to get the correct (previous) behavior.  Assuming that devel/test
repos don't generally sign packages.
=> Rename/Change yumrepos gpgcheck input arg. name.

roles/atomic_upgrade/defaults/main.yml, roles/atomic_upgrade/tasks/main.yml, roles/installed/defaults/main.yml, roles/installed/tasks/main.yml, roles/updated/defaults/main.yml
Ansible docs state "operations that take longer than the ssh
timeout will fail".  This is certainly more likely to happen with large
package installs/atomic updates depending on networking conditions.
Reduce dependency on low-latency networking by monitoring the
install/update via polling.
=> Fix: timeouts during install/upgrade

__exekutir__/cleanup_before_job.yml, __exekutir__/setup_before_job.yml, docs/source/overview.rst, exekutir.xn, test_exekutir_xn.sh
The first commit tries to explain what's fixed here (it's an ansible-ism).  The two other commits are just supporting changes and related uninttest updates.
When any task fails, ansible skips all other tasks for that host, but
continues with tasks for other hosts.  Because pre-job.xn setup tasks
are mandatory, change the default behavior of ansible to exit
immediatly when any task fails.  The play argument
``any_errors_fatal: true`` accomplishes this.
The exception to the above is during the cleanup transition.  That
context must always complete (successful or not).  In other words,
whether or not kommandir re/discovery is successful, there are still
additional tasks to perform on the exekutir.  Allow those cases
by NOT setting ``any_errors_fatal`` in cleanup_before_job.yml
=> fixup! Simplify fix fatal exit

__exekutir__/inventory/host_vars/kommandir.yml, __exekutir__/roles/kommandir_workspace_setup/tasks/main.yml
Since git module_arg depth:2 fails for python-bugzilla repo, omitting it for this repo and setting it individually for the other repos. Please review.
=> Modifying git depth

kommandir/fixme_migrate_roles/kommandir/tasks/openstack.yml
Update openstack to use os_server module instead of nova_compute to
create/show storage volume using command cinder rather than nova
Signed-off-by: Afom Michael <tmichael@redhat.com>
=> fixup! Use os_server module instead of nova_compute for openstack

.test_openstack_TestDestroy.test_found.json, .test_openstack_TestDestroy.test_missing.json, .test_openstack_TestDestroy.test_other.json, .test_openstack_TestDiscoverCreate.test_floating.json, .test_openstack_TestDiscoverCreate.test_found.json, .test_openstack_TestDiscoverCreate.test_missing.json, .test_openstack_TestDiscoverCreate.test_partial.json, README.rst, exekutir/inventory/group_vars/openstack/all.yml, kommandir/bin/adept_openstack.py, kommandir/bin/openstack.py, kommandir/bin/openstack_destroy.py, kommandir/bin/openstack_discover_create.py, test_openstack.py
Work-in-progress (it's a mess).  Releasing early for review/feedback (yes I know it needs functions).  Incomplete and minimally tested at this point (copy-paste into python CLI).  Only supports kommandir discovery (not creation or removal yet).  Requires ``clouds.yml`` to exist in ``$WORKSPACE`` (as in, you put it there).  Though supporting ``OS_*`` env. vars. can be done as well.  I'm not sure if I want to continue using the REST API (portable, less library version sensitive, very fast) or just shell-out to the ``openstack`` CLI (ease of implementation, but possibly more version sensitive)
=> Add openstack kommandir provisioning script

group_vars/openstack, vars/peon_defaults.yml, vars/peons.yml
Also, some peon name prefixes changed for clarity,
(e.g. rhelatomic-latest -> rhelatomic-dockerlatest)
and for consistency with new upgrade-testing:
e.g. rhel-7.2upgraded-dockerlatest
=> Drop CentOS testing, add Upgrade testing

roles/peon/tasks/peons_guuid.yml, vars/peons.yml
This value is used for looking up the image when creating a peon.
However, when used as mapping keys, the object type is important.
This supports simple typos like treating a two-component version
as if it was a floating point number.  Since the image map uses
string version number keys, the floating-point numbers from the peon
definition wouldn't match, resulting in an error.  This commit
both fixes the source of the problem, and adds a conversion
of all peon version values, into strings.
=> Fix version number vs string

roles/autotested/templates/subtests.ini.j2
Should fix this ADEPT failure in docker create test:
Get https://registery.access.redhat.com/v1/_ping: dial tcp: lookup registery.access.redhat.com on 172.16.12.2:53: no such host: expected 0; got 1
=> typo fix: registry.access.redhat.com

roles/autotested/templates/subtests.ini.j2
The upstream configuration (https://github.com/autotest/autotest-docker/pull/707) is generic.  Some repo-masking is needed to test this to pass under RHEL and RHELAH so that extraneous test repositories can't get in the way.  Exact same reason why "run_install" is specialized.
=> Specialize run/run_update test for RHEL

roles/autotested/templates/control.ini.j2
After autotest/autotest-docker #710 it's not necessary to re-specify all
non-default control.ini options.  Only those which should override them
need to be written.
=> Update control file template for autotested role

group_vars/openstack, vars/peons.yml
Also use the 'latest' (pre-updated) image for 7.3 testing speed.
=> Add pre-release testing for 7.4

group_vars/openstack, vars/peons.yml
It doesn't work due to internal yum repository dependencies
=> Kill pre-release tesitng

files/slave_container.xn, roles/sync_back/tasks/main.yml
At the end of cleanup, some directories in the kommandir's workspace are
removed after sync'ing them back to the starting host.  This partly
prevents rapid consumption of workspace cache on the kommandir VM.
However, it was removing the ``adept`` directory, which is required by
external callers to perform additional cleanup steps.  Don't remove this
directory.
=> Don't kill the tool needed to do the work

exekutir/ansible.cfg, exekutir/cleanup_after_job.yml, exekutir/roles/kommandir_up/tasks/main.yml, exekutir/run_before_job.yml, exekutir/setup_after_job.yml, exekutir/setup_before_job.yml, kommandir/ansible.cfg, kommandir/cleanup.yml, kommandir/kommandir_before_peons.yml, kommandir/peon_setup.yml, kommandir/setup.yml
Limit all fact gathering to just the facter minimal fact collection.
This resolves problems with timeouts gathering facts on "localhost"
where the vast majority are irrelivent.
=> Fix timeout gathering exekutir facts

exekutir/inventory/host_vars/kommandir.yml
These make installing Ansible via pip easier, should locking down
it's version per-job be needed in the future.
=> Fix a few non-essential missing deps on the Kommandir

exekutir/roles/workspace_cleanup/tasks/main.yml
The find module is already restricted to workspace, specifying it again
in the pattern (stored in "result") causes no files to be matched.
=> Fix default glob used when cleaning workspace

roles/liverestore_enabled/tasks/main.yml
Based on RHEL ``7.4`` testing, a missing option in the docker/latest unit
files was found.  With this commit, the only special/additional setup
steps for enabling liverestore are:
* Starting with daemons stopped, ``container-storage-setup``
hasn't run yet.
* Rely on runc package to have tweaked kernel params (all platforms)
* Copy ``/usr/lib/systemd/system/docker*.service`` into
``/etc/systemd/system/``
* In the copies, replace ``MountFlags=slave`` with ``KillMode=process``
* Start/enable docker or docker-latest services (implied
``container-storage-setup``)
=> Fix liverestore peon configuration

kommandir/cleanup.yml, kommandir/inventory/group_vars/recycled.yml, kommandir/inventory/nocloud, kommandir/peon_creation.yml, kommandir/peon_setup.yml, kommandir/roles/peon_up/defaults/main.yml
Since setting up a peon takes a non-trivial amount of time, it makes
sense to support recycling.  When a peon is a member of the ``recycled``
group, then it will not be provisioned or have any low-level setup
performed.
It's assumed from the start, that the peon's ``kommandir_workspace/inventory/host_vars``
file is correct/current. Which probably means copying it there
via a ``extra_exekutir_setup`` or ``extra_kommandir_setup`` command
(since the workspace is wiped out during ``exekutir_workspace_setup``).
Also nuke all references to ``nocloud`` peons, since the destinction
doesn't make much sense and wasn't ever used/applied correctly.
=> Support recycle pre-existing & kill nocloud-peons

kommandir/roles/autotested/tasks/test_image_fqin.yml
Apparently using '\' to escape newlines in YAML concatenated-values
doesn't work.  However even without them, jinja2 insists on tagging
a newline on the end.  Remove the '\' characters, but also trim off
the trailing newline.
=> Fix including newlines/escape chars in FQIN

kommandir/bin/adept_openstack.py, kommandir/inventory/group_vars/openstack.yml
On an active Kommandir, it's possible for jobs to contend with eachother
over allocating floating IP addresses.  Partially address this by
using a system-wide lock directory.  This was previously setup in a
prior commit, but not realized via kommandir/inventory/group_vars/openstack.yml
This does not address the issue where multiple kommandirs all contend
for public IPs, however solving that is non-trivial and out-of-scope for
this small fix.
Also include a fix to adept_openstack.py that results in CWD being
used as the lock dir because of default '' (empty string) parameter value.
=> Fix not using global lock on kommandir

exekutir/roles/exekutir_workspace_setup/defaults/main.yml, exekutir/roles/exekutir_workspace_setup/tasks/main.yml, kommandir/inventory/group_vars/fedora/pre_raw_cmds.yml
Rather than using a complicated list and filtering exekutir_vars.yml
to setup kommandir_vars.yml, just use a simple list of
excludes/includes.  Also update related comments.
=> Simplify kommandir_vars.yml init. and comments

.travis.yml, exekutir.xn, exekutir/ansible.cfg, kommandir/ansible.cfg, test_files.py
If there's a case where this is a bad idea, a role will need to be
written to configure it on/off.
=> Force color-output, always.

adept.py, test_adept.py
Previously, a logic bug caused any variable pulled
from the environment by a variable/from_env block
that included a default attribute, to always use
the default value.  Fix this by correcting the logic
and adding a unittest to cover the failure-mode.
=> Fix from_env var w/ default always ''

exekutir/roles/exekutir_workspace_setup/defaults/main.yml, exekutir/roles/workspace_cleanup/tasks/main.yml, jobs/basic/templates/control.ini.j2, kommandir/cleanup.yml, kommandir/roles/rebooted/defaults/main.yml, kommandir/roles/rebooted/tasks/main.yml, kommandir/roles/unsubscribed/tasks/main.yml
The peon_up role is included after rebooting.  However, frequently the
rebooted role is only applied ``when needs_reboot == True``.  Since that
conditional is applied to all tasks, and the rebooted role sets it false
before including peon_up, no peon_up checks will run.  Fix this by
changing the order of setting needs_reboot in the reboot role.
Also include a small fix to avoid cleaning up the workspace when not
running with a cloud-based (shared) kommandir.
=> Fix not skipping peon_up after reboot

exekutir/ansible.cfg, kommandir/ansible.cfg, kommandir/peon_creation.yml, kommandir/peon_setup.yml, kommandir/run.yml
In ansible 2.3.1, an error message is emitted if the free strategy is used and the ``add_host`` module appears anywhere in a play.
=> Enable setting up peons using 'free' strategy

.test_openstack_TestDiscoverCreate.test_floating.json, .test_openstack_TestDiscoverCreate.test_missing.json, kommandir/bin/adept_openstack.py, test_openstack.py
Even with the best locking possible, there's still exists the chance
of different kommandirs or ``nocloud`` kommandirs steeling already
assigned Floating IPs.  Instead of picking the first (perceived) available
floating IP, pick one at random.  However, undo this for unittesting
so that behavior is predictable.
=> Help floating-IP associate openstack race

kommandir/inventory/group_vars/fedoratomic/autotested.yml, kommandir/roles/autotested/templates/subtests.ini.j2
If it's there, then docker feels compelled to try and contact the
localhost registry (which doesn't exist). Instead, if the
default test image was deleted, we want tests to fail as early as
possible.
Also updated documentation. This change needs to be paired with
a similar change being made in Docker Autotest
=> Fix use of namespace for fedora_test_image

.travis.yml, docs/source/variables.inc.rst, exekutir/roles/exekutir_workspace_setup/defaults/main.yml, exekutir/roles/exekutir_workspace_setup/tasks/main.yml, kommandir/peon_setup.yml, kommandir/roles/autotested/defaults/main.yml, kommandir/roles/autotested/tasks/collect_results.yml, kommandir/roles/autotested/tasks/parse_prd.yml, kommandir/roles/autotested/tasks/run.yml, kommandir/roles/failed_peon_junit/defaults/main.yml, kommandir/roles/failed_peon_junit/tasks/main.yml, kommandir/roles/lvm/tasks/main.yml
* Secure passing of external variable values, by filtering them after
parsing.  This prevents a multi-line incoming string value from
corrupting or leaking/overwriting other values.  Previously this was
possible by blindly using 'lineinfile' to set YAML values in
kommandir_vars.yml
* Define new variable ``pull_request_description`` and add
documentation.  Include this value from ``exekutir_vars.yml``
when producing ``kommandir_vars.yml``.
* Define a new variable, ``docker_autotest_mmargs`` for the Autotested
role.  Document this in the role's defaults ``main.yml`` file.
When set, it's contents will be passed to the ``--args`` option
of autotest-local via an environment variable.  The indirect reference
blocks attempts to escape the confines of quoting.
* Add safe-parsing of a magic string …
=> Support passthrough of --args to Docker Autotest

.test_openstack_TestDestroy.test_found.json, .test_openstack_TestDiscoverCreate.test_privsize.json, kommandir/bin/adept_openstack.py, kommandir/roles/autotested/tasks/parse_prd.yml
Avoid any setting of ``docker_autotest_mmargs`` if the magic string is
not found, or is found more than once.  Without this, the entire
``pull_request_description`` gets passed into ``autotest-local``'s
``--args`` option.
=> Critical fixes

README.rst, kommandir/roles/autotested/files/known_failures.txt, kommandir/roles/autotested/tasks/setup.yml
A disposable PR to help test https://github.com/autotest/autotest-docker/pull/761 because I'm lazy and probably screwed up the ``known_failures.txt`` file somehow...
=> autotested: Copy known_failures.txt

kommandir/roles/autotested/files/known_failures.txt
Looks like an old version of oci-umount bundled with docker
=> known_failures: add fedora atomic one

kommandir/roles/sysconfig_docker/defaults/main.yml, kommandir/roles/sysconfig_docker/tasks/main.yml
In the reccomended configuration for OpenStack, some
container-networking opterations can fail due to docker or the kernel
not properly configuring the MTU properly.  This is a long-standing
problem and as of this commit, still being worked on.  As a workaround
for all cases, force the docker and docker-latest MTU size for
containers to 1400 (recommended configuration value).  Add an option
to easily disable this workaround in the future if needed.  Otherwise
leaving this in is basically inconsequential.
=> Add workaround for OpenStack networking bug

exekutir/inventory/group_vars/openstack.yml, exekutir/roles/kommandir_discovered/files/kommandir_userdata.yml
By default, openstack provisioning does not grow the root filesystem.
This is done to allow easier customizing of the layout from w/in
ansible.  However, for the kommandir, all available disk space is
required for jobs.  Drop a custom userdata file, and reference it
from the openstack group variable file.
=> Fix: Kommandir disk space

kommandir/roles/common/tasks/main.yml
In some cases, a playbook running on the kommandir may want to use an
alternate private key file.  This is supported by setting the expected
variable in job.xn, for the ansible-playbook command.  However in the
``common`` role, the ``ansible_private_key_file`` fact hard-codes
the value instead of looking it up from the environment.  Fix this.
=> Fix kommandir PB ignore $ANSIBLE_PRIVATE_KEY_FILE

exekutir/roles/exekutir_workspace_setup/tasks/main.yml
Should a directory exist with useful files inside the exekutir's
workspace, they would be clobbered when setting up the initial
pre-sync. kommandir workspace.  This is because the exekutir's
results is always a symlink into results synchronized from kommandir (by
design).  Fix this by moving any existing files before creating the symlink.
=> Fix clobbering pre-existing results

exekutir/roles/common/tasks/main.yml
This was originally done for security purposes, to block
private hostnames and repo URLs from being accessable on peons
when synchronizing workspace/cache.  However, this is
security-overreach by ADEPT, because it activly removes all choice from
the job author, as to what needs protecting and what doesn't.  In cases
where repository details should not be shared, there are other hooks
for doing this (ex ``extra_exekutir_setup`` and
``extra_kommandir_setup``)
=> Fix: Excluding .git directory during sync

adept.py, exekutir.xn
Originally, ``adept.py`` did not have the ability to allow selecting or
setting env. vars within a transition file.  Therefor the default
set of variables selected for pass-through was quite wide.
Since adding a ``variable`` action-item to the standard, it's now
possible to select env. vars for pass-through and/or set static values.
The more general set of default variables in ``adept.py`` can therefor
be safely paired back to a more sane minimum.  Including only variables
which are extremely common and safe to allow in by default.
=> Fix oversharing of env. vars

kommandir/inventory/group_vars/fedora/storage.yml, kommandir/inventory/group_vars/rhel/storage.yml, kommandir/peon_setup.yml, kommandir/roles/partitioned/defaults/main.yml, kommandir/roles/partitioned/tasks/main.yml
Previously this was quite buggy/unreliable, so to avoid messing up
disks, we just fed in the command-line directly.  Now the module seems
more mature, and using it should be far more stable/standard that doing
anything custom.
=> Switch to using ansible parted module

kommandir/bin/adept_openstack.py, kommandir/inventory/group_vars/centos/extra_peon_setup_cmnds.yml, kommandir/inventory/group_vars/rhel/extra_peon_setup_cmnds.yml, kommandir/inventory/group_vars/rhelatomic/extra_peon_setup_cmnds.yml
* Simple update for centos + openstack provisioner.
* Prior "workaround" commit runs contrary to purpose of 18a530694c3d0ee90f54582d7c616fdad2a4d81d
=> Centos openstack + Revert

exekutir/roles/exekutir_workspace_setup/tasks/main.yml, kommandir/inventory/group_vars/openstack/creation_destruction.yml
ADEPT's setup should behave idempotently, meaning contexts can be
applied more than once.  A bug in the exekutir_workspace_setup role
relating to pre-existing results was preventing this.  Also,
the default openstack provisioning command was configured to
fail if a peon already existed.  Change this to be more tolerant
of existing peons.
=> Fix running setup more than once

kommandir/roles/peon_up/defaults/main.yml, kommandir/roles/peon_up/tasks/main.yml
The 'ping' module requires python on the remote host.  Instead, use the
raw module to run /bin/true.  The python requirement is handled later in
another playbook.
=> Fix peon_up again: No python on Fedora

.test_openstack_TestDiscoverCreate.test_preserve.json, .test_openstack_TestReap.test_death.json, .test_openstack_TestReap.test_forever_bad.json, .test_openstack_TestReap.test_forever_good.json, .test_openstack_TestReap.test_verbose.json, adept.py, kommandir/bin/adept_openstack.py, kommandir/bin/flock.py, kommandir/bin/openstack_reap.py, test_adept.py, test_openstack.py
This is handy for implimenting 'reaper' based cleanup strategy.
Establish a metadata key ``preserve`` for every created server,
with a default value of ``False``.  If a VM needs to be preserved,
then the openstack command or API can be used to easily flip
this key ``True``.
=> Set OpenStack metadata preserve on create

exekutir/inventory/group_vars/openstack.yml
These are always identified by having a non-empty kommandir_name_prefix.
When that variable is empty, set the preservation flag to indefinate.
=> Don't preserve test-kommandir VMs in OpenStack

.travis_typo_check.sh, jobs/basic/README, jobs/basic/roles/autotest_installed/tasks/main.yml, jobs/podman_basic/README, jobs/podman_basic/inventory/hosts.yml, jobs/podman_basic/kommandir_vars.yml, jobs/podman_basic/roles/autotest_executed/defaults/main.yml, jobs/podman_basic/roles/autotest_executed/meta/main.yml, jobs/podman_basic/roles/autotest_executed/tasks/main.yml, jobs/podman_basic/roles/autotest_executed/vars/main.yml, jobs/podman_basic/roles/has_swap/defaults/main.yml, jobs/podman_basic/roles/has_swap/tasks/main.yml, jobs/podman_basic/roles/podman_autotest/defaults/main.yml, jobs/podman_basic/roles/podman_autotest/meta/main.yml, jobs/podman_basic/roles/podman_autotest/tasks/main.yml, jobs/podman_basic/roles/podman_autotest/vars/main.yml, jobs/podman_basic/run.yml, jobs/podman_basic/setup.yml
Supporting changes needed to help share bunches of common elements between the 'basic' job and the new 'podman_basic' job.  The actual podman-autotest bits (also temporary) live upstream, as a branch to autotest-docker.  This PR just lays down most of the ground work, as there's still a lot of heavy-lifting needed to actually make the tests function.  That effort is happening in parallel, and therefor there will likely be further changes needed here, later.
=> Add temporary podman job and supporting changes

jobs/podman_basic/roles/autotest_executed/defaults/main.yml
I remember Ed mentioning this job takes 40-something minutes.  Fix the
default timeout to exceed that by a healthy margin.  Giving it lots
of breathing room is fine, since generally nobody is sitting around
waiting on an automated job.  I don't believe there are any shorter
timeouts in higher (execution) layers this will collide with.
=> Increase default timeout for podman job

kommandir/bin/adept_openstack.py, test_verbosefilter.py
It looks like the logger can be called with a non-string
object as a message; this resulted today in a failure
in VerboseFilter:
if record.msg.startswith('>'):
AttributeError: 'exceptions.IndexError' object has no attribute 'startswith'
Solution: use getMessage() instead of directly accessing
the .msg element; that should reliably give us a string.
Add test.
=> VerboseFilter() : handle non-string log messages

kommandir/bin/adept_openstack.py, test_verbosefilter.py
The last "fix" to VerboseFilter was broken: it would
replace a string like ("this is a %s", "test") with
("this is a test", "test") which would then yield:
TypeError: not all arguments converted during string processing
Solution: don't replace the logging string. To handle
the previous issue (logger getting called with Exceptions),
in VerboseFilter, simply ignore non-string messages
=> VerboseFilter: handle format strings

jobs/basic/inventory/hosts.yml, jobs/podman_basic/inventory/hosts.yml, kommandir/inventory/group_vars/openstack/peon_images.yml
=> Bump RHEL 'latest' image names to 7.6
