cevich/ADEPT

- cleanup.yml
- redhat_release.yml
- roles/autotest_docker/tasks/test_image_fqin.yml
- roles/redhat_release/tasks/main.yml
> Fix hosts not being added to subscribed group

- roles/autotest_docker/tasks/main.yml
> Add debug statement for autotest_docker variable

- roles/autotested/tasks/configure_control.yml
> Only change timeout if it's a number

- cleanup.yml
- group_vars/subscribed.sample
- roles/subscribed/defaults/main.yml
- roles/subscribed/tasks/main.yml
- roles/unsubscribed/tasks/main.yml
> Add optional tollerance for subscription failures

- roles/autotested/tasks/configure_control.yml
- roles/autotested/tasks/configure_defaults.yml
- roles/autotested/tasks/main.yml
> No backup modified Autotest/Docker Autotest files

- roles/autotested/handlers/main.yml
- roles/autotested/tasks/main.yml
> Collect list of installed rpms

- group_vars/autotested.sample
- roles/autotested/defaults/main.yml
- roles/autotested/tasks/configure_defaults.yml
> Add parameter to set docker_timeout

- roles/autotested/handlers/main.yml
- roles/autotested/tasks/main.yml
> Don't fail if some result collecting fails

- roles/autotested/handlers/main.yml
> No fail missing + remove trailing slash on dest

- roles/rebooted/defaults/main.yml
- roles/rebooted/tasks/main.yml
> Fix race-condition when uptime is very short

- redhat_release.yml
- roles/rhelah/tasks/main.yml
- roles/se_enabled/defaults/main.yml
- roles/se_enabled/handlers/main.yml
- roles/se_enabled/tasks/main.yml
> Ensure selinux is enabled/enforcing targeted policy

- roles/autotested/defaults/main.yml
- roles/autotested/tasks/main.yml
- roles/rhelah/tasks/main.yml
> Print cause of BZ1313540 workaorund failure

- adept.py
- roles/autotested/tasks/main.yml
- roles/common/tasks/is_atomic.yml
- roles/common/tasks/main.yml
> Stat file faster tha running command

- roles/autotested/tasks/configure_control.yml
> Fix variable name in timeout set conditional

- roles/autotested/defaults/main.yml
- roles/autotested/tasks/configure_control.yml
- roles/autotested/tasks/main.yml
- roles/rebooted/tasks/main.yml
Otherwise results (good/bad) will not be collected for debugging.
> Ignore Autotest execution errors

- group_vars/kommandir
> Update kommandir image UUID

- group_vars/centos/storage.yml
- group_vars/openstack
- group_vars/rhel/storage.yml
- peons.yml
- roles/atomic_upgrade/meta/main.yml
- roles/autotested/meta/main.yml
- roles/autotested/templates/control.ini.j2
- roles/installed/meta/main.yml
- roles/kommandir/meta/main.yml
- roles/lvm/meta/main.yml
- roles/openstack/meta/main.yml
- roles/partitioned/meta/main.yml
- roles/peon/meta/main.yml
- roles/rebooted/meta/main.yml
- roles/slave/meta/main.yml
- roles/subscribed/meta/main.yml
- roles/sync_back/meta/main.yml
- roles/sync_out/meta/main.yml
Mostly all niggly-details.  The ``build/git_path`` one is most important.
> Fix build/git_path, Role deps, Linear Strategy, Atomic Storage Reset

- group_vars/fedora/autotested.yml
- group_vars/fedoratomic/autotested.yml
- group_vars/openstack
- group_vars/rhel/autotested.yml
- group_vars/rhelatomic/autotested.yml
- roles/autotested/defaults/main.yml
- roles/autotested/templates/control.ini.j2
This is just moving some things that use to be defined externally, and making it easier to customize when needed.  Not a complete/perfect fix, but incrementally moving things in a better direction.
> Consolidate external variables / templates

- roles/partitioned/tasks/main.yml
> Tolerate sfdisk fail on empty/corrupt disk label

- group_vars/fedora/installed_rpms.yml
- roles/atomic_upgrade/tasks/main.yml
- roles/autotested/tasks/produce_results.yml
- roles/autotested/tasks/test_image_fqin.yml
- roles/installed/tasks/main.yml
- roles/lvm/defaults/main.yml
- roles/services/tasks/main.yml
- roles/updated/tasks/main.yml
- vars/peons.yml
Mostly Fedora-support related + one special request
> Barrel-o-fixes

- roles/subscribed/tasks/main.yml
> Workaround missing implementation

- files/cleanup_exit.yml
- roles/autotested/tasks/collect_results.yml
- roles/autotested/tasks/main.yml
- roles/autotested/tasks/produce_results.yml
- roles/autotested/templates/cooked_results.junit.j2
- run.yml
> Allow autotest client to fail

- roles/autotested/templates/subtests.ini.j2
> Fix RHEL's run/run_install config.

- README.rst
> Kill misleading / not working docs.

- group_vars/kommandir
- roles/kommandir/defaults/main.yml
- roles/kommandir/tasks/openstack.yml
- roles/slave/tasks/cleanup.yml
Original commit was missing a set of curly-braces.
> Fix: Slow down rate of kommandir disk filling

- roles/atomic_upgrade/defaults/main.yml
- roles/atomic_upgrade/tasks/main.yml
- roles/installed/defaults/main.yml
- roles/installed/tasks/main.yml
- roles/updated/defaults/main.yml
Reverts cevich/autotest-docker-enabled-product-testing#107
> Revert "Fix: timeouts during install/upgrade"

- files/slave_container.xn
> Add kommandir (slave) task to prune old workspace files

- docs/source/index.rst
- docs/source/variables.rst
D.N.R.  Just a placeholder for now
> Add documentation reference for important variables

- README.rst
- docs/source/hacking.rst
> Update missing doc. building deps. from readme

- exekutir/roles/kommandir_destroyed/defaults/main.yml
> Fix duplicate default variable

- group_vars/fedora/installed_rpms.yml
- group_vars/rhel/installed_rpms.yml
- group_vars/rhel/yumrepos.yml
- group_vars/rhelatomic/yumrepos.yml
- roles/liverestore_enabled/tasks/main.yml
> New docker vers. need rpm for deferred removal

- roles/liverestore_enabled/tasks/main.yml
> Fix liverestore_enable typo

- kommandir/inventory/group_vars/centos/autotested.yml
- kommandir/inventory/group_vars/centos/installed_rpms.yml
- kommandir/inventory/group_vars/centos/is_enterprise.yml
- kommandir/inventory/group_vars/centos/openstack.yml
- kommandir/inventory/group_vars/centos/storage.yml
- kommandir/inventory/group_vars/openstack/peon_images.yml
- kommandir/inventory/host_vars/centos7-docker-latest.yml
Not actually used, but there in case it's needed
> Add back limited CentOS support

- kommandir/inventory/group_vars/openstack/creation_destruction.yml
- kommandir/roles/docker-storage-setup/tasks/main.yml
- kommandir/roles/sysconfig_docker/defaults/main.yml
- kommandir/roles/sysconfig_docker/tasks/main.yml
* When no 'peon_size' fact specified, openstack provisioning would fail.
Add a conditional to fix this.
* For d-s-s and sysconfig_docker, behavior WRT docker-latest changes for
RHEL 7.5+.  Add conditionals to fix this.
> Fix a few misc items

- kommandir/inventory/group_vars/centos/extra_peon_setup_cmnds.yml
- kommandir/inventory/group_vars/rhel/extra_peon_setup_cmnds.yml
- kommandir/inventory/group_vars/rhelatomic/extra_peon_setup_cmnds.yml
> Workaround bug-fix side-effect in 7.5+

- .test_openstack_TestReap.test_death.json
- .test_openstack_TestReap.test_dryrun.json
- .test_openstack_TestReap.test_parse_err.json
- kommandir/bin/adept_openstack.py
- kommandir/bin/flock.py
- test_openstack.py
Resolves #213 and Resolves #215
> Combination of PR #213 and #215

- test_verbosefilter.py
Make sure that the new VerboseFilter works as expected, and
does not inadvertently affect any levels other than INFO
> Tests for VerboseFilter

- kommandir/bin/adept_openstack.py
- test_openstack.py
Remove much duplication and dangerous hardcoded knowledge
about the names and numbers of allowed operations. End
goal is to make built-in operations more modular, allowing
for simple expanding (or removing) of operations.
Also: clarified some confusing/misleading parts.
> adept_openstack: refactor, allow expanded operations

- venv-cmd.sh
> Fix signal handling from venv-cmd.sh in container
